### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by chinedu40** [faulander/P4S#27]
Hi,

When trying to run P4S on port 1337 i get Bad request (400) error.

**Comment by faulander** [comment]
Firststart did run without any errors? Are the containers running? A little more info would be helpful.

**Comment by chinedu40** [comment]
yes i ran ./firststart.prod.sh and ./startapp.prod.sh with no problems. containers are running. I am running it on a synology NAS using docker. It does seem to work on MacOS docker.

**Comment by faulander** [comment]
unfortunatelly i do not have a synology to test. If the containers run, can you access /admin on the server? 
Do you run it locally on your Mac when it works?

If yes. Change the settings in .env.prod to DJANGO_ALLOWED_HOSTS=*

If this did work, then you should add the local ip adress from where you are calling the website to the original DJANGO_ALLOWED_HOSTS setting, then it should also work remotely.

**Comment by chinedu40** [comment]
> unfortunatelly i do not have a synology to test. If the containers run, can you access /admin on the server? Do you run it locally on your Mac when it works? If yes. Change the settings in .env.prod to DJANGO_ALLOWED_HOSTS=* If this did work, then you should add the local ip adress from where you are calling the website to the original DJANGO_ALLOWED_HOSTS setting, then it should also work remotely.

Hi, just to let you know changing DJANGO_ALLOWED_HOSTS to =* worked. Is there any issue in leaving this as * rather than specifying the IP?

**Comment by faulander** [comment]
@chinedu40 : It depends on if your synology is reachable from outside your local network. it's a security issue. It just means that Nginx will allow all requests, no matter where they origin from.

In short: if your synology is only reachable internally you're fine.
