### ISSUE TITLE
Updating of shows

### ISSUE THREAD

**Issue by MadDucks** [faulander/P4S#31]
Is P4S as is, in docker form, supposed to update the shows that are in development?  My instance doesn't seem to update the new shows (some are in there that have gone to production)

**Comment by faulander** [comment]
it should as long as TVMaze provides the correct data. 
Do you have an example show?

**Comment by MadDucks** [comment]
Sure how would you like the data?  Here is a screen capture for example.

Both War of the Worlds and Resident Alien have either shown or are showing.

**Comment by MadDucks** [comment]
<img width="1201" alt="Screen Shot 2021-02-15 at 11 29 13 AM" src="https://user-images.githubusercontent.com/7400119/107992793-a9d4b880-6f96-11eb-855c-da09a3172e1b.png">
<img width="1208" alt="Screen Shot 2021-02-15 at 11 28 42 AM" src="https://user-images.githubusercontent.com/7400119/107992795-aa6d4f00-6f96-11eb-9c7d-3dc9fad73ad5.png">

**Comment by MadDucks** [comment]
<img width="1208" alt="Screen Shot 2021-02-15 at 11 28 42 AM" src="https://user-images.githubusercontent.com/7400119/107992910-f1f3db00-6f96-11eb-8c86-c702e8938f6e.png">
<img width="1201" alt="Screen Shot 2021-02-15 at 11 29 13 AM" src="https://user-images.githubusercontent.com/7400119/107992915-f3bd9e80-6f96-11eb-8e66-8aa95e056aef.png">

**Comment by faulander** [comment]
Thanks. The names are good enough. I check the TVMaze Data as soon as i can.

**Comment by faulander** [comment]
fixed in Master
